CREATE TYPE selfcare_type AS ENUM (
    'emotional',
    'intellectual',
    'spiritual',
    'physical'
);

CREATE TABLE lovemore_selfcares(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    date_modified TIMESTAMPTZ NOT NULL DEFAULT now(),
    type selfcare_type NOT NULL,
    rating INTEGER NOT NULL CHECK (rating > 0 AND rating < 6),
    user_id INTEGER REFERENCES lovemore_users(id) ON DELETE CASCADE NOT NULL
)