CREATE TABLE lovemore_moods(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mood_level INTEGER NOT NULL CHECK (mood_level > 0 AND mood_level < 11),
    energy_level INTEGER NOT NULL CHECK (energy_level > 0 AND energy_level < 11),
    date_modified TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id INTEGER REFERENCES lovemore_users(id) ON DELETE CASCADE NOT NULL
)