CREATE TABLE lovemore_goals(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    emotional INTEGER CHECK (emotional > -1 AND emotional < 11),
    intellectual INTEGER CHECK (intellectual > -1 AND intellectual < 11),
    physical INTEGER CHECK (physical > -1 AND physical < 11),
    spiritual INTEGER CHECK (spiritual > -1 AND spiritual < 11),
    user_id INTEGER REFERENCES lovemore_users(id) ON DELETE CASCADE NOT NULL
);