CREATE TABLE lovemore_goals(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    emotional INTEGER CHECK (emotional > 0 AND emotional < 11),
    mental INTEGER CHECK (mental > 0 AND mental < 11),
    physical INTEGER CHECK (physical > 0 AND physical < 11),
    spiritual INTEGER CHECK (spiritual > 0 AND spiritual < 11),
    user_id INTEGER REFERENCES lovemore_users(id) ON DELETE CASCADE NOT NULL
);